# Generated by Django 5.1.3 on 2024-11-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='RegisterUser',
        ),
    ]
