# Generated by Django 5.1.3 on 2024-11-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_login_registeruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
