# Generated by Django 5.1.3 on 2024-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_registeruser_email_alter_registeruser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('qntd', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registeruser',
            name='rent_bike',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
