# Generated by Django 5.1.3 on 2024-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_bikerent_registeruser_rent_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerent',
            name='qntd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='rent_bike',
            field=models.IntegerField(null=True),
        ),
    ]
