# Generated by Django 5.1.3 on 2024-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_bikerent_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerent',
            name='hour',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='hour',
            field=models.DateField(null=True, verbose_name='Horario alugado'),
        ),
    ]
