# Generated by Django 5.1.3 on 2024-11-21 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_bikerent_hour_registeruser_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('total_bikes', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.bikestation')),
            ],
        ),
        migrations.DeleteModel(
            name='BikeRent',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='rent_bike',
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.registeruser'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='current_rent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_renting', to='map.rent', verbose_name='Aluguel ativo'),
        ),
    ]
