# Generated by Django 5.1.3 on 2024-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_bikestation_rent_delete_bikerent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
